/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoremImport } from './routes/lorem'
import { Route as DolorImport } from './routes/dolor'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LoremRoute = LoremImport.update({
  path: '/lorem',
  getParentRoute: () => rootRoute,
} as any)

const DolorRoute = DolorImport.update({
  path: '/dolor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dolor': {
      id: '/dolor'
      path: '/dolor'
      fullPath: '/dolor'
      preLoaderRoute: typeof DolorImport
      parentRoute: typeof rootRoute
    }
    '/lorem': {
      id: '/lorem'
      path: '/lorem'
      fullPath: '/lorem'
      preLoaderRoute: typeof LoremImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dolor': typeof DolorRoute
  '/lorem': typeof LoremRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dolor': typeof DolorRoute
  '/lorem': typeof LoremRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dolor': typeof DolorRoute
  '/lorem': typeof LoremRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dolor' | '/lorem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dolor' | '/lorem'
  id: '__root__' | '/' | '/dolor' | '/lorem'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DolorRoute: typeof DolorRoute
  LoremRoute: typeof LoremRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DolorRoute: DolorRoute,
  LoremRoute: LoremRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dolor",
        "/lorem"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dolor": {
      "filePath": "dolor.tsx"
    },
    "/lorem": {
      "filePath": "lorem.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
