/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PostImport } from './routes/post'

// Create/Update Routes

const PostRoute = PostImport.update({
  path: '/post',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/post': typeof PostRoute
}

export interface FileRoutesByTo {
  '/post': typeof PostRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/post': typeof PostRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/post'
  fileRoutesByTo: FileRoutesByTo
  to: '/post'
  id: '__root__' | '/post'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PostRoute: typeof PostRoute
}

const rootRouteChildren: RootRouteChildren = {
  PostRoute: PostRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/post"
      ]
    },
    "/post": {
      "filePath": "post.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
